import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "el" | "en" | "sv" | "fi";

export const languageNames: Record<Language, string> = {
  el: "ΕΛ",
  en: "EN",
  sv: "SV",
  fi: "FI",
};

export const translations = {
  el: {
    nav_home: "Αρχική", nav_services: "Υπηρεσίες", nav_packages: "Πακέτα",
    nav_portfolio: "Portfolio", nav_why_us: "Γιατί Εμάς", nav_contact: "Επικοινωνία",
    nav_cta: "Ζητήστε Προσφορά",
    hero_label: "Cyprus Digital Agency",
    hero_headline: "Χτίζουμε ψηφιακές εμπειρίες που φέρνουν",
    hero_accent: "ΑΠΟΤΕΛΕΣΜΑΤΑ",
    hero_subtitle: "Premium ιστοσελίδες, branding και digital στρατηγική για επιχειρήσεις που θέλουν να ξεχωρίσουν.",
    hero_btn_primary: "Κλείστε μια Συνάντηση", hero_btn_secondary: "Δείτε τη Δουλειά μας",
    trust_years: "Χρόνια Εμπειρίας", trust_dedication: "Αφοσίωση στον Πελάτη", trust_communication: "Γρήγορη Επικοινωνία",
    services_heading: "Οι Υπηρεσίες μας",
    service_web_title: "Δημιουργία Ιστοσελίδας", service_web_desc: "Σχεδιάζουμε γρήγορες, επαγγελματικές ιστοσελίδες που μετατρέπουν επισκέπτες σε πελάτες.",
    service_social_title: "Social Media Management", service_social_desc: "Δημιουργούμε περιεχόμενο που αυξάνει το engagement και χτίζει κοινότητα.",
    service_graphics_title: "Γραφιστικά & Δημιουργικά", service_graphics_desc: "Οπτικό υλικό υψηλής αισθητικής για κάθε ψηφιακό κανάλι.",
    service_logo_title: "Logo & Branding", service_logo_desc: "Χτίζουμε ταυτότητα μάρκας που μένει αξέχαστη.",
    service_google_title: "Google Business Profile", service_google_desc: "Κάνουμε την επιχείρησή σας ορατή στις τοπικές αναζητήσεις.",
    service_ads_title: "Διαφημίσεις Facebook & Instagram", service_ads_desc: "Στοχευμένες καμπάνιες που φέρνουν πραγματικά αποτελέσματα.",
    how_heading_1: "Πώς μπορούμε να", how_heading_2: "σας βοηθήσουμε",
    how_step1_title: "Στρατηγική", how_step1_desc: "Αναλύουμε τους στόχους σας και χτίζουμε το σωστό πλάνο ανάπτυξης.",
    how_step2_title: "Σχεδιασμός", how_step2_desc: "Δημιουργούμε οπτική ταυτότητα και εμπειρίες που μένουν αξέχαστες.",
    how_step3_title: "Ανάπτυξη", how_step3_desc: "Υλοποιούμε τη λύση με ακρίβεια, ταχύτητα και προσοχή στη λεπτομέρεια.",
    how_step4_title: "Launch & Scale", how_step4_desc: "Ξεκινάμε, παρακολουθούμε και αναπτύσσουμε τα αποτελέσματά σας.",
    portfolio_heading: "Δείγματα δουλειάς",
    portfolio_item1_title: "Ιστοσελίδα Εστιατορίου", portfolio_item1_result: "+45% Αύξηση Πωλήσεων",
    portfolio_item3_result: "Brand Identity από Μηδέν",
    portfolio_item4_title: "Καμπάνια Διαφημίσεων Gym", portfolio_item4_result: "3x ROAS σε 30 Ημέρες",
    packages_heading: "Στρατηγικές λύσεις για την ανάπτυξή σας",
    packages_customized: "Προσαρμοσμένο στις ανάγκες σας",
    packages_footer_note: "Τα πακέτα προσαρμόζονται ανάλογα με τις ανάγκες της επιχείρησής σας.",
    pkg_launch_tagline: "Ιδανικό για επιχειρήσεις που ξεκινούν την ψηφιακή τους παρουσία.",
    pkg_growth_tagline: "Για επιχειρήσεις που είναι έτοιμες να αναπτυχθούν και να αποκτήσουν leads.",
    pkg_scale_tagline: "Για brands που θέλουν πλήρη ψηφιακή κυριαρχία στην αγορά τους.",
    pkg_cta_quote: "Ζητήστε Προσφορά", pkg_cta_talk: "Μιλήστε Μαζί Μας", pkg_cta_meeting: "Κλείστε Συνάντηση",
    content_heading: "Δημιουργία Περιεχομένου",
    content_subtitle: "Επαγγελματικές φωτογραφίες & βίντεο που αναδεικνύουν το brand σας",
    content_samples: "Δείγματα Δουλειάς", content_cta_question: "Θέλετε περιεχόμενο που ξεχωρίζει;",
    content_cta_btn: "Ζητήστε Προσφορά",
    content_f1_title: "Φωτογράφιση χώρου & προϊόντων", content_f1_desc: "Επαγγελματικές λήψεις που αναδεικνύουν την ταυτότητα της επιχείρησής σας.",
    content_f2_title: "Βίντεο για social media & διαφημίσεις", content_f2_desc: "Cinematic βίντεο σχεδιασμένα για engagement, αναγνωρισιμότητα και αύξηση πωλήσεων.",
    content_f3_title: "Reels & short-form περιεχόμενο", content_f3_desc: "Δυναμικά short videos για Instagram, TikTok και Facebook που αυξάνουν το reach.",
    content_f4_title: "Brand storytelling videos", content_f4_desc: "Αφηγηματικά βίντεο που χτίζουν εμπιστοσύνη και ενισχύουν το brand image σας.",
    content_p1_title: "Φωτογράφιση Προϊόντων", content_p3_title: "Προϊόντα & Branding",
    whyus_label: "Γιατί CYDigital", whyus_heading_1: "Γιατί να επιλέξετε την",
    whyus_paragraph: "Συνδυάζουμε στρατηγική, αισθητική και τεχνολογία για να δημιουργούμε digital παρουσίες που ξεχωρίζουν και φέρνουν πραγματικά αποτελέσματα.",
    whyus_cta: "Μιλήστε μαζί μας",
    whyus_r1_title: "Strategy-First Προσέγγιση", whyus_r1_desc: "Κάθε απόφαση βασίζεται σε στόχο, δεδομένα και ανάπτυξη.",
    whyus_r2_title: "Premium Εκτέλεση", whyus_r2_desc: "Custom λύσεις με προσεγμένο design και καθαρή εμπειρία χρήστη.",
    whyus_r3_title: "Results-Driven Νοοτροπία", whyus_r3_desc: "Δεν σχεδιάζουμε απλά όμορφα. Σχεδιάζουμε για αποτέλεσμα.",
    whyus_r4_title: "Κλιμακωτή Ανάπτυξη", whyus_r4_desc: "Συστήματα που μεγαλώνουν μαζί με την επιχείρησή σας.",
    whyus_r5_title: "Τοπική Γνώση", whyus_r5_desc: "Κατανοούμε την αγορά, την κουλτούρα και τις ανάγκες της Κύπρου.",
    whyus_r6_title: "Αποκλειστική Εξυπηρέτηση", whyus_r6_desc: "Δουλεύουμε με περιορισμένο αριθμό πελατών για καλύτερη ποιότητα.",
    testimonials_heading: "Τι Λένε οι Πελάτες μας",
    t1_quote: "Η CYDigital αναβάθμισε πλήρως την online παρουσία μας. Το website είναι γρήγορο, premium και μας φέρνει περισσότερες κρατήσεις.",
    t1_role: "Ιδιοκτήτης Εστιατορίου", t1_result: "+60% κρατήσεις",
    t2_quote: "Το branding και το περιεχόμενο μας πλέον δείχνουν επαγγελματικά. Οι πελάτες καταλαβαίνουν αμέσως την αξία μας.",
    t2_role: "Beauty Salon Owner", t2_result: "Premium brand image",
    t3_quote: "Οι καμπάνιες μας έγιναν πιο στοχευμένες και αποδοτικές. Είδαμε καλύτερα leads και χαμηλότερο κόστος διαφήμισης.",
    t3_role: "Γυμναστήριο FitLife", t3_result: "2x καλύτερα leads",
    cta_label: "Ξεκινήστε Σήμερα", cta_heading_1: "Ας χτίσουμε την επόμενη", cta_heading_2: "ψηφιακή σας επιτυχία",
    cta_subtitle: "Premium ιστοσελίδες, branding και digital στρατηγική για επιχειρήσεις που θέλουν να ξεχωρίσουν.",
    cta_btn_primary: "Κλείστε Συνάντηση", cta_btn_secondary: "Δείτε τις Λύσεις μας",
    contact_heading: "Επικοινωνία", contact_subheading_1: "Ας μιλήσουμε για", contact_subheading_2: "την επιχείρησή σας",
    contact_desc: "Συμπληρώστε τη φόρμα και θα επικοινωνήσουμε μαζί σας εντός 24 ωρών για να συζητήσουμε τις ανάγκες σας.",
    contact_trust1: "Δωρεάν αρχική αξιολόγηση", contact_trust2: "Προτάσεις προσαρμοσμένες στις ανάγκες σας", contact_trust3: "Καμία δέσμευση",
    contact_label_name: "Το όνομά σας", contact_label_company: "Επιχείρηση",
    contact_label_phone: "Τηλέφωνο επικοινωνίας", contact_label_email: "Email",
    contact_label_city: "Περιοχή", contact_label_service: "Υπηρεσία που σας ενδιαφέρει",
    contact_label_message: "Μήνυμα (Προαιρετικό)",
    contact_placeholder_name: "π.χ. Γιάννης Παπαδόπουλος", contact_placeholder_company: "π.χ. Το Καφέ μου",
    contact_placeholder_phone: "π.χ. 99 123456", contact_placeholder_city: "π.χ. Λευκωσία",
    contact_select_placeholder: "Επιλέξτε...",
    contact_service_web: "Δημιουργία Ιστοσελίδας", contact_service_social: "Social Media Management",
    contact_service_graphics: "Γραφιστικά & Δημιουργικά", contact_service_branding: "Logo & Branding",
    contact_service_google: "Google Business Profile", contact_service_ads: "Διαφημίσεις Facebook & Instagram",
    contact_service_content: "Δημιουργία Περιεχομένου",
    contact_message_placeholder: "Πείτε μας λίγα λόγια για τις ανάγκες σας...",
    contact_submit_loading: "Αποστολή...", contact_submit: "Ζητήστε Προσφορά",
    contact_privacy: "Τα στοιχεία σας παραμένουν απολύτως εμπιστευτικά.",
    contact_error: "Κάτι πήγε στραβά. Δοκιμάστε ξανά ή επικοινωνήστε μαζί μας απευθείας.",
    contact_success_title: "Ευχαριστούμε!",
    contact_success_desc: "Θα επικοινωνήσουμε σύντομα μαζί σας για να συζητήσουμε τις ανάγκες της επιχείρησής σας.",
    contact_send_new: "Αποστολή Νέου Μηνύματος",
    val_name: "Το όνομα πρέπει να έχει τουλάχιστον 2 χαρακτήρες", val_company: "Το όνομα επιχείρησης είναι υποχρεωτικό",
    val_phone: "Μη έγκυρος αριθμός τηλεφώνου", val_email: "Μη έγκυρο email",
    val_city: "Η περιοχή είναι υποχρεωτική", val_service: "Επιλέξτε υπηρεσία",
    footer_menu: "Μενού", footer_contact: "Επικοινωνία", footer_follow: "Ακολουθήστε Μας",
    footer_desc: "Premium Digital Agency για επιχειρήσεις που θέλουν να ξεχωρίζουν.",
    footer_response_title: "Απαντάμε Συνήθως", footer_response_desc: "Μέσα σε 24 ώρες",
    footer_rights: "Με επιφύλαξη παντός δικαιώματος.", footer_terms: "Όροι Χρήσης", footer_privacy_link: "Πολιτική Απορρήτου",
    floating_cta: "Ζητήστε Προσφορά",
  },
  en: {
    nav_home: "Home", nav_services: "Services", nav_packages: "Packages",
    nav_portfolio: "Portfolio", nav_why_us: "Why Us", nav_contact: "Contact",
    nav_cta: "Get a Quote",
    hero_label: "Cyprus Digital Agency",
    hero_headline: "We build digital experiences that deliver",
    hero_accent: "RESULTS",
    hero_subtitle: "Premium websites, branding and digital strategy for businesses that want to stand out.",
    hero_btn_primary: "Book a Meeting", hero_btn_secondary: "See Our Work",
    trust_years: "Years of Experience", trust_dedication: "Client Dedication", trust_communication: "Fast Communication",
    services_heading: "Our Services",
    service_web_title: "Website Creation", service_web_desc: "We design fast, professional websites that convert visitors into clients.",
    service_social_title: "Social Media Management", service_social_desc: "We create content that boosts engagement and builds community.",
    service_graphics_title: "Graphics & Creative", service_graphics_desc: "High-quality visual content for every digital channel.",
    service_logo_title: "Logo & Branding", service_logo_desc: "We build brand identities that are unforgettable.",
    service_google_title: "Google Business Profile", service_google_desc: "We make your business visible in local searches.",
    service_ads_title: "Facebook & Instagram Ads", service_ads_desc: "Targeted campaigns that deliver real results.",
    how_heading_1: "How we can", how_heading_2: "help you",
    how_step1_title: "Strategy", how_step1_desc: "We analyse your goals and build the right growth plan.",
    how_step2_title: "Design", how_step2_desc: "We create visual identities and experiences that are unforgettable.",
    how_step3_title: "Development", how_step3_desc: "We deliver the solution with precision, speed and attention to detail.",
    how_step4_title: "Launch & Scale", how_step4_desc: "We launch, monitor and grow your results.",
    portfolio_heading: "Work Samples",
    portfolio_item1_title: "Restaurant Website", portfolio_item1_result: "+45% Sales Growth",
    portfolio_item3_result: "Brand Identity from Scratch",
    portfolio_item4_title: "Gym Ad Campaign", portfolio_item4_result: "3x ROAS in 30 Days",
    packages_heading: "Strategic solutions for your growth",
    packages_customized: "Tailored to your needs",
    packages_footer_note: "Packages are customised according to your business needs.",
    pkg_launch_tagline: "Ideal for businesses starting their digital presence.",
    pkg_growth_tagline: "For businesses ready to grow and acquire leads.",
    pkg_scale_tagline: "For brands seeking full digital domination in their market.",
    pkg_cta_quote: "Get a Quote", pkg_cta_talk: "Talk to Us", pkg_cta_meeting: "Book a Meeting",
    content_heading: "Content Creation",
    content_subtitle: "Professional photos & videos that elevate your brand",
    content_samples: "Work Samples", content_cta_question: "Want content that stands out?",
    content_cta_btn: "Get a Quote",
    content_f1_title: "Space & Product Photography", content_f1_desc: "Professional shots that showcase the identity of your business.",
    content_f2_title: "Video for social media & ads", content_f2_desc: "Cinematic videos designed for engagement, recognition and sales growth.",
    content_f3_title: "Reels & short-form content", content_f3_desc: "Dynamic short videos for Instagram, TikTok and Facebook that increase reach.",
    content_f4_title: "Brand storytelling videos", content_f4_desc: "Narrative videos that build trust and strengthen your brand image.",
    content_p1_title: "Product Photography", content_p3_title: "Products & Branding",
    whyus_label: "Why CYDigital", whyus_heading_1: "Why choose",
    whyus_paragraph: "We combine strategy, aesthetics and technology to create digital presences that stand out and deliver real results.",
    whyus_cta: "Talk to Us",
    whyus_r1_title: "Strategy-First Approach", whyus_r1_desc: "Every decision is based on goals, data and growth.",
    whyus_r2_title: "Premium Execution", whyus_r2_desc: "Custom solutions with refined design and clean user experience.",
    whyus_r3_title: "Results-Driven Mindset", whyus_r3_desc: "We don't just design beautifully. We design for results.",
    whyus_r4_title: "Scalable Growth", whyus_r4_desc: "Systems that grow alongside your business.",
    whyus_r5_title: "Local Knowledge", whyus_r5_desc: "We understand the market, culture and needs of Cyprus.",
    whyus_r6_title: "Exclusive Service", whyus_r6_desc: "We work with a limited number of clients for better quality.",
    testimonials_heading: "What Our Clients Say",
    t1_quote: "CYDigital completely upgraded our online presence. The website is fast, premium and brings us more bookings.",
    t1_role: "Restaurant Owner", t1_result: "+60% bookings",
    t2_quote: "Our branding and content now look professional. Clients immediately understand our value.",
    t2_role: "Beauty Salon Owner", t2_result: "Premium brand image",
    t3_quote: "Our campaigns became more targeted and efficient. We saw better leads and lower advertising costs.",
    t3_role: "FitLife Gym", t3_result: "2x better leads",
    cta_label: "Get Started Today", cta_heading_1: "Let's build your next", cta_heading_2: "digital success",
    cta_subtitle: "Premium websites, branding and digital strategy for businesses that want to stand out.",
    cta_btn_primary: "Book a Meeting", cta_btn_secondary: "See Our Solutions",
    contact_heading: "Contact", contact_subheading_1: "Let's talk about", contact_subheading_2: "your business",
    contact_desc: "Fill in the form and we will get back to you within 24 hours to discuss your needs.",
    contact_trust1: "Free initial consultation", contact_trust2: "Proposals tailored to your needs", contact_trust3: "No obligation",
    contact_label_name: "Your name", contact_label_company: "Business",
    contact_label_phone: "Phone number", contact_label_email: "Email",
    contact_label_city: "Location", contact_label_service: "Service of interest",
    contact_label_message: "Message (Optional)",
    contact_placeholder_name: "e.g. John Smith", contact_placeholder_company: "e.g. My Café",
    contact_placeholder_phone: "e.g. +357 99 123456", contact_placeholder_city: "e.g. Nicosia",
    contact_select_placeholder: "Select...",
    contact_service_web: "Website Creation", contact_service_social: "Social Media Management",
    contact_service_graphics: "Graphics & Creative", contact_service_branding: "Logo & Branding",
    contact_service_google: "Google Business Profile", contact_service_ads: "Facebook & Instagram Ads",
    contact_service_content: "Content Creation",
    contact_message_placeholder: "Tell us a bit about your needs...",
    contact_submit_loading: "Sending...", contact_submit: "Get a Quote",
    contact_privacy: "Your details remain completely confidential.",
    contact_error: "Something went wrong. Please try again or contact us directly.",
    contact_success_title: "Thank you!",
    contact_success_desc: "We will get in touch with you soon to discuss your business needs.",
    contact_send_new: "Send New Message",
    val_name: "Name must be at least 2 characters", val_company: "Business name is required",
    val_phone: "Invalid phone number", val_email: "Invalid email",
    val_city: "Location is required", val_service: "Please select a service",
    footer_menu: "Menu", footer_contact: "Contact", footer_follow: "Follow Us",
    footer_desc: "Premium Digital Agency for businesses that want to stand out.",
    footer_response_title: "We Usually Reply", footer_response_desc: "Within 24 hours",
    footer_rights: "All rights reserved.", footer_terms: "Terms of Use", footer_privacy_link: "Privacy Policy",
    floating_cta: "Get a Quote",
  },
  sv: {
    nav_home: "Hem", nav_services: "Tjänster", nav_packages: "Paket",
    nav_portfolio: "Portfolio", nav_why_us: "Varför Oss", nav_contact: "Kontakt",
    nav_cta: "Begär offert",
    hero_label: "Cyprus Digital Agency",
    hero_headline: "Vi bygger digitala upplevelser som levererar",
    hero_accent: "RESULTAT",
    hero_subtitle: "Premium webbplatser, varumärkesbyggande och digital strategi för företag som vill sticka ut.",
    hero_btn_primary: "Boka ett möte", hero_btn_secondary: "Se vårt arbete",
    trust_years: "Års erfarenhet", trust_dedication: "Klientdedikation", trust_communication: "Snabb kommunikation",
    services_heading: "Våra tjänster",
    service_web_title: "Webbplatsskapande", service_web_desc: "Vi designar snabba, professionella webbplatser som omvandlar besökare till kunder.",
    service_social_title: "Social Media Management", service_social_desc: "Vi skapar innehåll som ökar engagemanget och bygger gemenskap.",
    service_graphics_title: "Grafik & Kreativt", service_graphics_desc: "Visuellt material av hög kvalitet för varje digitalt kanal.",
    service_logo_title: "Logo & Varumärke", service_logo_desc: "Vi bygger varumärkesidentiteter som är oförglömliga.",
    service_google_title: "Google Business Profile", service_google_desc: "Vi gör ditt företag synligt i lokala sökningar.",
    service_ads_title: "Facebook & Instagram-annonser", service_ads_desc: "Riktade kampanjer som ger verkliga resultat.",
    how_heading_1: "Hur vi kan", how_heading_2: "hjälpa dig",
    how_step1_title: "Strategi", how_step1_desc: "Vi analyserar dina mål och bygger rätt tillväxtplan.",
    how_step2_title: "Design", how_step2_desc: "Vi skapar visuella identiteter och upplevelser som är oförglömliga.",
    how_step3_title: "Utveckling", how_step3_desc: "Vi levererar lösningen med precision, hastighet och uppmärksamhet på detaljer.",
    how_step4_title: "Launch & Scale", how_step4_desc: "Vi lanserar, övervakar och växer dina resultat.",
    portfolio_heading: "Arbetsexempel",
    portfolio_item1_title: "Restaurangwebbplats", portfolio_item1_result: "+45% försäljningstillväxt",
    portfolio_item3_result: "Varumärkesidentitet från grunden",
    portfolio_item4_title: "Gym-annonskampanj", portfolio_item4_result: "3x ROAS på 30 dagar",
    packages_heading: "Strategiska lösningar för din tillväxt",
    packages_customized: "Anpassat till dina behov",
    packages_footer_note: "Paketen anpassas efter ditt företags behov.",
    pkg_launch_tagline: "Idealiskt för företag som startar sin digitala närvaro.",
    pkg_growth_tagline: "För företag redo att växa och skaffa leads.",
    pkg_scale_tagline: "För varumärken som söker full digital dominans på sin marknad.",
    pkg_cta_quote: "Begär offert", pkg_cta_talk: "Prata med oss", pkg_cta_meeting: "Boka ett möte",
    content_heading: "Innehållsskapande",
    content_subtitle: "Professionella foton & videor som lyfter ditt varumärke",
    content_samples: "Arbetsexempel", content_cta_question: "Vill du ha innehåll som sticker ut?",
    content_cta_btn: "Begär offert",
    content_f1_title: "Lokal- & produktfotografering", content_f1_desc: "Professionella bilder som visar upp ditt företags identitet.",
    content_f2_title: "Video för sociala medier & annonser", content_f2_desc: "Cinematiska videor designade för engagemang, igenkänning och försäljningstillväxt.",
    content_f3_title: "Reels & kortformsinnehåll", content_f3_desc: "Dynamiska korta videor för Instagram, TikTok och Facebook som ökar räckvidden.",
    content_f4_title: "Brand storytelling-videor", content_f4_desc: "Berättande videor som bygger förtroende och stärker ditt varumärke.",
    content_p1_title: "Produktfotografering", content_p3_title: "Produkter & Varumärke",
    whyus_label: "Varför CYDigital", whyus_heading_1: "Varför välja",
    whyus_paragraph: "Vi kombinerar strategi, estetik och teknik för att skapa digitala närvaro som sticker ut och levererar verkliga resultat.",
    whyus_cta: "Prata med oss",
    whyus_r1_title: "Strategy-First-metod", whyus_r1_desc: "Varje beslut baseras på mål, data och tillväxt.",
    whyus_r2_title: "Premium genomförande", whyus_r2_desc: "Anpassade lösningar med förfinad design och ren användarupplevelse.",
    whyus_r3_title: "Resultatdriven mentalitet", whyus_r3_desc: "Vi designar inte bara snyggt. Vi designar för resultat.",
    whyus_r4_title: "Skalbar tillväxt", whyus_r4_desc: "System som växer tillsammans med ditt företag.",
    whyus_r5_title: "Lokal kunskap", whyus_r5_desc: "Vi förstår marknaden, kulturen och behoven på Cypern.",
    whyus_r6_title: "Exklusiv service", whyus_r6_desc: "Vi arbetar med ett begränsat antal kunder för bättre kvalitet.",
    testimonials_heading: "Vad våra kunder säger",
    t1_quote: "CYDigital uppgraderade helt vår onlinenärvaro. Webbplatsen är snabb, premium och ger oss fler bokningar.",
    t1_role: "Restaurangägare", t1_result: "+60% bokningar",
    t2_quote: "Vår branding och vårt innehåll ser nu professionellt ut. Kunderna förstår omedelbart vårt värde.",
    t2_role: "Beauty Salon Owner", t2_result: "Premium brand image",
    t3_quote: "Våra kampanjer blev mer riktade och effektiva. Vi såg bättre leads och lägre annonskostnader.",
    t3_role: "FitLife Gym", t3_result: "2x bättre leads",
    cta_label: "Kom igång idag", cta_heading_1: "Låt oss bygga ditt nästa", cta_heading_2: "digitala framgång",
    cta_subtitle: "Premium webbplatser, varumärkesbyggande och digital strategi för företag som vill sticka ut.",
    cta_btn_primary: "Boka ett möte", cta_btn_secondary: "Se våra lösningar",
    contact_heading: "Kontakt", contact_subheading_1: "Låt oss prata om", contact_subheading_2: "ditt företag",
    contact_desc: "Fyll i formuläret så återkommer vi inom 24 timmar för att diskutera dina behov.",
    contact_trust1: "Kostnadsfri initial konsultation", contact_trust2: "Förslag anpassade efter dina behov", contact_trust3: "Ingen förpliktelse",
    contact_label_name: "Ditt namn", contact_label_company: "Företag",
    contact_label_phone: "Telefonnummer", contact_label_email: "E-post",
    contact_label_city: "Ort", contact_label_service: "Intresserad tjänst",
    contact_label_message: "Meddelande (Valfritt)",
    contact_placeholder_name: "t.ex. Anders Eriksson", contact_placeholder_company: "t.ex. Mitt Café",
    contact_placeholder_phone: "t.ex. +358 41 123456", contact_placeholder_city: "t.ex. Helsingfors",
    contact_select_placeholder: "Välj...",
    contact_service_web: "Webbplatsskapande", contact_service_social: "Social Media Management",
    contact_service_graphics: "Grafik & Kreativt", contact_service_branding: "Logo & Varumärke",
    contact_service_google: "Google Business Profile", contact_service_ads: "Facebook & Instagram-annonser",
    contact_service_content: "Innehållsskapande",
    contact_message_placeholder: "Berätta lite om dina behov...",
    contact_submit_loading: "Skickar...", contact_submit: "Begär offert",
    contact_privacy: "Dina uppgifter förblir helt konfidentiella.",
    contact_error: "Något gick fel. Försök igen eller kontakta oss direkt.",
    contact_success_title: "Tack!",
    contact_success_desc: "Vi återkommer snart för att diskutera ditt företags behov.",
    contact_send_new: "Skicka nytt meddelande",
    val_name: "Namnet måste ha minst 2 tecken", val_company: "Företagsnamn är obligatoriskt",
    val_phone: "Ogiltigt telefonnummer", val_email: "Ogiltig e-post",
    val_city: "Ort är obligatorisk", val_service: "Välj en tjänst",
    footer_menu: "Meny", footer_contact: "Kontakt", footer_follow: "Följ oss",
    footer_desc: "Premium Digital Agency för företag som vill sticka ut.",
    footer_response_title: "Vi svarar vanligtvis", footer_response_desc: "Inom 24 timmar",
    footer_rights: "Alla rättigheter förbehållna.", footer_terms: "Användarvillkor", footer_privacy_link: "Integritetspolicy",
    floating_cta: "Begär offert",
  },
  fi: {
    nav_home: "Etusivu", nav_services: "Palvelut", nav_packages: "Paketit",
    nav_portfolio: "Portfolio", nav_why_us: "Miksi Me", nav_contact: "Yhteystiedot",
    nav_cta: "Pyydä tarjous",
    hero_label: "Cyprus Digital Agency",
    hero_headline: "Rakennamme digitaalisia kokemuksia, jotka tuottavat",
    hero_accent: "TULOKSIA",
    hero_subtitle: "Premium verkkosivustot, brändäys ja digitaalinen strategia yrityksille, jotka haluavat erottua.",
    hero_btn_primary: "Varaa tapaaminen", hero_btn_secondary: "Katso työtämme",
    trust_years: "Vuotta kokemusta", trust_dedication: "Asiakasomistautuminen", trust_communication: "Nopea viestintä",
    services_heading: "Palvelumme",
    service_web_title: "Verkkosivuston luominen", service_web_desc: "Suunnittelemme nopeita, ammattimaisia verkkosivustoja, jotka muuttavat kävijät asiakkaiksi.",
    service_social_title: "Sosiaalisen median hallinta", service_social_desc: "Luomme sisältöä, joka lisää sitoutumista ja rakentaa yhteisöä.",
    service_graphics_title: "Grafiikka & Luova sisältö", service_graphics_desc: "Korkealaatuista visuaalista materiaalia jokaiselle digitaaliselle kanavalle.",
    service_logo_title: "Logo & Brändi", service_logo_desc: "Rakennamme brändi-identiteettejä, jotka jäävät mieleen.",
    service_google_title: "Google Business Profile", service_google_desc: "Teemme yrityksestäsi näkyvän paikallisissa hauissa.",
    service_ads_title: "Facebook & Instagram -mainokset", service_ads_desc: "Kohdistetut kampanjat, jotka tuottavat todellisia tuloksia.",
    how_heading_1: "Miten voimme", how_heading_2: "auttaa sinua",
    how_step1_title: "Strategia", how_step1_desc: "Analysoimme tavoitteesi ja rakennamme oikean kasvusuunnitelman.",
    how_step2_title: "Suunnittelu", how_step2_desc: "Luomme visuaalisia identiteettejä ja kokemuksia, jotka jäävät mieleen.",
    how_step3_title: "Kehitys", how_step3_desc: "Toteutamme ratkaisun tarkasti, nopeasti ja huomioimalla yksityiskohdat.",
    how_step4_title: "Julkaisu & Kasvu", how_step4_desc: "Julkaisemme, seuraamme ja kasvamme tuloksiasi.",
    portfolio_heading: "Työnäytteitä",
    portfolio_item1_title: "Ravintolan verkkosivusto", portfolio_item1_result: "+45% myynnin kasvu",
    portfolio_item3_result: "Brändi-identiteetti alusta asti",
    portfolio_item4_title: "Kuntosalin mainoskampanja", portfolio_item4_result: "3x ROAS 30 päivässä",
    packages_heading: "Strategiset ratkaisut kasvullesi",
    packages_customized: "Räätälöity tarpeisiisi",
    packages_footer_note: "Paketit räätälöidään yrityksesi tarpeiden mukaan.",
    pkg_launch_tagline: "Ihanteellinen yrityksille, jotka aloittavat digitaalisen läsnäolonsa.",
    pkg_growth_tagline: "Yrityksille, jotka ovat valmiita kasvamaan ja hankkimaan liidejä.",
    pkg_scale_tagline: "Brändeille, jotka haluavat täyden digitaalisen hallitsevan aseman markkinoillaan.",
    pkg_cta_quote: "Pyydä tarjous", pkg_cta_talk: "Ota yhteyttä", pkg_cta_meeting: "Varaa tapaaminen",
    content_heading: "Sisällöntuotanto",
    content_subtitle: "Ammattimaiset kuvat & videot, jotka nostavat brändiäsi",
    content_samples: "Työnäytteitä", content_cta_question: "Haluatko sisältöä, joka erottuu?",
    content_cta_btn: "Pyydä tarjous",
    content_f1_title: "Tila- & tuotefotografia", content_f1_desc: "Ammattimaiset kuvaukset, jotka esittelevät yrityksesi identiteettiä.",
    content_f2_title: "Video sosiaaliseen mediaan & mainoksiin", content_f2_desc: "Elokuvamaiset videot, jotka on suunniteltu sitoutumiseen, tunnistettavuuteen ja myynnin kasvuun.",
    content_f3_title: "Reels & lyhytmuotoinen sisältö", content_f3_desc: "Dynaamiset lyhyet videot Instagramiin, TikTokiin ja Facebookiin, jotka lisäävät näkyvyyttä.",
    content_f4_title: "Brändin tarinankerrontavideot", content_f4_desc: "Kerronnalliset videot, jotka rakentavat luottamusta ja vahvistavat brändi-imagoasi.",
    content_p1_title: "Tuotefotografia", content_p3_title: "Tuotteet & Brändi",
    whyus_label: "Miksi CYDigital", whyus_heading_1: "Miksi valita",
    whyus_paragraph: "Yhdistämme strategian, estetiikan ja teknologian luodaksemme digitaalisia läsnäoloja, jotka erottuvat ja tuottavat todellisia tuloksia.",
    whyus_cta: "Ota yhteyttä",
    whyus_r1_title: "Strategia ensin -lähestymistapa", whyus_r1_desc: "Jokainen päätös perustuu tavoitteisiin, tietoihin ja kasvuun.",
    whyus_r2_title: "Premium-toteutus", whyus_r2_desc: "Räätälöidyt ratkaisut hienostuneella designilla ja selkeällä käyttäjäkokemuksella.",
    whyus_r3_title: "Tuloslähtöinen ajattelutapa", whyus_r3_desc: "Emme vain suunnittele kauniisti. Suunnittelemme tuloksia varten.",
    whyus_r4_title: "Skaalautuva kasvu", whyus_r4_desc: "Järjestelmät, jotka kasvavat yrityksesi mukana.",
    whyus_r5_title: "Paikallinen tuntemus", whyus_r5_desc: "Ymmärrämme Kyproksen markkinat, kulttuurin ja tarpeet.",
    whyus_r6_title: "Eksklusiivinen palvelu", whyus_r6_desc: "Työskentelemme rajoitetun asiakaskunnan kanssa paremman laadun takaamiseksi.",
    testimonials_heading: "Mitä asiakkaamme sanovat",
    t1_quote: "CYDigital uudisti verkkoläsnäolomme täysin. Verkkosivusto on nopea, premium ja tuo meille enemmän varauksia.",
    t1_role: "Ravintolan omistaja", t1_result: "+60% varaukset",
    t2_quote: "Brändäyksemme ja sisältömme näyttävät nyt ammattimaisilta. Asiakkaat ymmärtävät heti arvomme.",
    t2_role: "Beauty Salon Owner", t2_result: "Premium brand image",
    t3_quote: "Kampanjamme muuttuivat kohdennetummiksi ja tehokkaammiksi. Näimme parempia liidejä ja alhaisempia mainoskuluja.",
    t3_role: "FitLife Gym", t3_result: "2x paremmat liidit",
    cta_label: "Aloita tänään", cta_heading_1: "Rakennetaan seuraava", cta_heading_2: "digitaalinen menestyksesi",
    cta_subtitle: "Premium verkkosivustot, brändäys ja digitaalinen strategia yrityksille, jotka haluavat erottua.",
    cta_btn_primary: "Varaa tapaaminen", cta_btn_secondary: "Katso ratkaisujamme",
    contact_heading: "Yhteystiedot", contact_subheading_1: "Puhutaan", contact_subheading_2: "yrityksestäsi",
    contact_desc: "Täytä lomake ja otamme sinuun yhteyttä 24 tunnin sisällä keskustellaksemme tarpeistasi.",
    contact_trust1: "Maksuton alkukonsultaatio", contact_trust2: "Ehdotukset räätälöitynä tarpeisiisi", contact_trust3: "Ei sitoumuksia",
    contact_label_name: "Nimesi", contact_label_company: "Yritys",
    contact_label_phone: "Puhelinnumero", contact_label_email: "Sähköposti",
    contact_label_city: "Sijainti", contact_label_service: "Kiinnostava palvelu",
    contact_label_message: "Viesti (Valinnainen)",
    contact_placeholder_name: "esim. Mikko Virtanen", contact_placeholder_company: "esim. Kahvilani",
    contact_placeholder_phone: "esim. +358 41 1234567", contact_placeholder_city: "esim. Pietarsaari",
    contact_select_placeholder: "Valitse...",
    contact_service_web: "Verkkosivuston luominen", contact_service_social: "Sosiaalisen median hallinta",
    contact_service_graphics: "Grafiikka & Luova sisältö", contact_service_branding: "Logo & Brändi",
    contact_service_google: "Google Business Profile", contact_service_ads: "Facebook & Instagram -mainokset",
    contact_service_content: "Sisällöntuotanto",
    contact_message_placeholder: "Kerro meille hieman tarpeistasi...",
    contact_submit_loading: "Lähetetään...", contact_submit: "Pyydä tarjous",
    contact_privacy: "Tietosi pysyvät täysin luottamuksellisina.",
    contact_error: "Jokin meni pieleen. Yritä uudelleen tai ota meihin suoraan yhteyttä.",
    contact_success_title: "Kiitos!",
    contact_success_desc: "Otamme sinuun pian yhteyttä keskustellaksemme yrityksesi tarpeista.",
    contact_send_new: "Lähetä uusi viesti",
    val_name: "Nimen on oltava vähintään 2 merkkiä", val_company: "Yrityksen nimi on pakollinen",
    val_phone: "Virheellinen puhelinnumero", val_email: "Virheellinen sähköposti",
    val_city: "Sijainti on pakollinen", val_service: "Valitse palvelu",
    footer_menu: "Valikko", footer_contact: "Yhteystiedot", footer_follow: "Seuraa meitä",
    footer_desc: "Premium Digital Agency yrityksille, jotka haluavat erottua.",
    footer_response_title: "Vastaamme yleensä", footer_response_desc: "24 tunnin sisällä",
    footer_rights: "Kaikki oikeudet pidätetään.", footer_terms: "Käyttöehdot", footer_privacy_link: "Tietosuojakäytäntö",
    floating_cta: "Pyydä tarjous",
  },
} as const;

export type TranslationKey = keyof typeof translations.el;

interface LanguageContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: typeof translations.el;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "el",
  setLang: () => {},
  t: translations.el,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>("el");
  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
